### ISSUE TITLE
MFE not found

### ISSUE THREAD

**Issue by ibnudaqiqil** [SuperKogito/spafe#11]
i try this https://spafe.readthedocs.io/en/latest/features/mfcc.html, but got this "ImportError: cannot import name 'mfe' from 'spafe.features.mfcc'"

**Comment by SuperKogito** [comment]
Can you try to replicate this [one](https://github.com/SuperKogito/spafe/blob/master/examples/features_mfcc_example.ipynb)? did you install spafe from source or using pip? 
I think the problem is solved but the  pip version is not up todate.

**Comment by SuperKogito** [comment]
`mfe` seems to be outdated and only present in the docs. Thanks for reporting.
