### ISSUE TITLE
'value error: shapes not aligned' while using pncc

### ISSUE THREAD

**Issue by mohammadalihumayun** [SuperKogito/spafe#12]
>>> pnccs = pncc(sig,fs,13)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\old data\Python\Python35\lib\site-packages\spafe\features\pncc.py", line 205, in pncc
    b=gammatone_filter.T)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (400,46) and (257,26) not aligned: 46 (dim 1) != 257 (dim 0)
>>>

**Comment by SuperKogito** [comment]
Are you using the dev version (downloaded from GitHub) or the pip version (installed from Pypi)?
I think that I already fixed this error in the development version but did not publish it to pip yet.

**Comment by mohammadalihumayun** [comment]
hi. Thanx for your response. initially i had installed using pip. now after your reply i uninstalled and cloned from github. still got same error.

**Comment by SuperKogito** [comment]
I am sorry for the late response, I still have this in mind. It is weird that this still fails using the git version. Is it possible to provide a code snippet of what you are trying exactly and maybe a copy of your test file so I can narrow down the error quickly?
