### ISSUE TITLE
Value error: negative dimensions are not allowed when using spafe library

### ISSUE THREAD

**Issue by barrydjenaba** [SuperKogito/spafe#13]
I am working in audio files and I use this code to extract lfcc features:

audio_path = '03-01-02-02-01-01-01_norm.wav'

fs, sig = scipy.io.wavfile.read(audio_path) 

lfcc = lfcc(sig, 13) 

but I have this value error:

    negative dimensions are not allowed

I think that it is because my sig array has negative values, can you give me a way to fix it?
Thank you for yor help

**Comment by SuperKogito** [comment]
can you provide the full trace-back of the error and maybe the audio if possible?

**Comment by barrydjenaba** [comment]
i send you the audio by email beacuse i  can't insert it here. I just used this code :

import scipy.io.wavfile
import spafe.utils.vis as vis
from spafe.features.lfcc import lfcc
from spafe.features.lpc import lpc
audio_path = '03-01-05-01-01-01-01_norm_outNoise.wav'
fs, sig = scipy.io.wavfile.read(audio_path)
lpc  = lfcc(sig, 13)

**Comment by SuperKogito** [comment]
You did not specify a sampling rate value fs, use: `lpc  = lfcc(sig, fs, 13)`
