### ISSUE TITLE
Error in preprocessing

### ISSUE THREAD

**Issue by ngragaei** [SuperKogito/spafe#14]
frames[-1] = np.append(frames[-1], np.array([0]*(frame_length - len(frames[0]))))

TypeError: can't multiply sequence by non-int of type 'float'

**Comment by SuperKogito** [comment]
Hello,
Thank you for using Spafe and reporting this unexpected behavior.
can you please post the full trace-back of the error and the sampling rate of your audio ?

**Comment by ngragaei** [comment]
Thanks for reply!
sampling rate = 44100 
i realize that when i use sampling rate rather than the default one, the error appears. 
So is it possible to use another sampling rate and nfft?

**Comment by SuperKogito** [comment]
I think this is a bug in the code, inside of the `framing()` function:
https://github.com/SuperKogito/spafe/blob/214f8fd8bf6abcc6b890f061f21a3f4f3f8b73b0/spafe/utils/preprocessing.py#L54


For now, the code should work with `16000 Hz`,  `8000 Hz`. I will put this on top of the list of things to fix, but it might take some time until I can get to it.
If you want to to take on this, then go for it ;) I will gladly help with the PR :)

**Comment by ngragaei** [comment]
Many thanks

**Comment by MMohsinM** [comment]
Can we just make the frame length an integer before multiplying it with [0]?

**Comment by SuperKogito** [comment]
@MMohsinM  well that might work and solve the error but it might result in the last frame being smaller than the other frames. I think the safest solution here is probably defining the frames length and step as integers from the start: 

    frame_length = int(win_len * fs)
    frame_step = int(win_hop * fs)
