### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by shakeel608** [SuperKogito/spafe#16]
Every time I try to compute MFCC GFCC or any other feature, it gives 

ZeroDivisionError: integer division or modulo by zero

`  File "/home/shsheikh/.local/lib/python3.5/site-packages/spafe/features/bfcc.py", line 108, in bfcc
    win_hop=win_hop)
  File "/home/shsheikh/.local/lib/python3.5/site-packages/spafe/utils/preprocessing.py", line 86, in framing
    frames = stride_trick(sig, int(frame_length), int(frame_step))
  File "/home/shsheikh/.local/lib/python3.5/site-packages/spafe/utils/preprocessing.py", line 47, in stride_trick
    nrows = ((a.size - stride_length) // stride_step) + 1
ZeroDivisionError: integer division or modulo by zero
`

**Comment by SuperKogito** [comment]
Thank your for reporting. 
This seems to be somehow related to #14 .Can you please, show me your code and give me some information on the files you are dealing with? sampling rate/frequency? mono/ stereo?
