### ISSUE TITLE
Extra number of frames

### ISSUE THREAD

**Issue by VeejayG98** [SuperKogito/spafe#17]
When trying out the LPCC function, I noticed that 6 extra frames were added to the lpcc values. For eg-
For a 1 sec audio clip with fs=16KHz, if I use the default frame width as 25ms and 10 sec window rollover, I should technically get 100 lpcc feature vectors. However, I am getting 106 feature vectors. I have attached my code below. 

`from spafe.features.lpc import lpcc, lpc
import scipy.io.wavfile as sio
from spafe.utils import vis
fs,sig=sio.read("C:/Users/91789/Downloads/test.wav")
num_ceps = 13
lifter = 0
normalize = True
lpcs = lpc(sig=sig[0:fs], fs=fs, num_ceps=num_ceps)`

**Comment by SuperKogito** [comment]
This should be fixed in the newest version `v0.2.0`. If not please report again :)
