### ISSUE TITLE
Spafe citation

### ISSUE THREAD

**Issue by ngragaei** [SuperKogito/spafe#21]
How to cite spafe?

**Comment by SuperKogito** [comment]
This should do: 
- Malek, A. (2020). Spafe (Version 2.1) [Software]. Available from https://pypi.org/project/spafe/.

**Comment by SuperKogito** [comment]
One can use this 
```
@software{ayoubmalek2020,
author = {Ayoub Malek}, 
title = {spafe/spafe: 0.1.2}, month = Apr, year = 2020, version = {0.1.2}, 
url = {https://github.com/SuperKogito/spafe}
}
```
However, if you are looking to quote a paper, I suggest the relevant in code cited papers since Spafe does not have a paper yet, but I am working on it ;)

**Comment by Helias** [comment]
if you make a paper for it, remember to update the README with the BibTex code.

I suggest keeping open this issue until you make this paper and update the README 👍
