### ISSUE TITLE
Run examples has TypeError:

### ISSUE THREAD

**Issue by Amforever** [SuperKogito/spafe#22]
TypeError: dct(): incompatible function arguments. The following argument types are supported:
    1. (a: array, type: int, axes: object = None, inorm: int = 0, out: object = None, nthreads: int = 1) -> array

**Comment by DYL2233** [comment]
i have the same question

**Comment by DYL2233** [comment]
how to deal with it?

**Comment by SuperKogito** [comment]
show me the code, an input example file/ data, python version and your libraries versions (numpy, scipy) so I can try to replicate the error.

**Comment by DYL2233** [comment]
THANKS FOR YOUR REPLY! I have a project about speech enhancement based on the deep learning for my graduation. It's my first time use TensorFlow2.0 to set up CNN model. I wanna to
take the speech feature.(MFCC).My tutor recommend spafe to me. It's really nice.&nbsp;
My code and version information are packaged in the attachment.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperKogito/spafe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月15日(星期四) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperKogito/spafe] Run examples has TypeError: (#22)





 
show me the code, an input example file/ data, python version and your libraries versions (numpy, scipy) so I can try to replicate the error.

**Comment by SuperKogito** [comment]
I cannot see the code, so either try to post it here or send me an email (see my profile). I should be able to look at it this weekend and hopefully we can solve it.

**Comment by SuperKogito** [comment]
@DYL2233  I answered you email. 
This error proved to be related the scipy version. This will be fixed in an upcoming release. 
However for now make sure to use scipy version 1.3.1

**Comment by kabrate** [comment]
> @DYL2233 I answered you email.
> This error proved to be related the scipy version. This will be fixed in an upcoming release.
> However for now make sure to use scipy version 1.3.1

Than you !!

**Comment by DYL2233** [comment]
The procedure can proceed smoothly. Thanks to you, I can continue my mid-term defense. If there are other questions in the follow-up, I will definitely communicate with you, thank you------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月23日(星期五) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperKogito/spafe] Run examples has TypeError: (#22)
