### ISSUE TITLE
AttributeError: module 'spafe.utils.vis' has no attribute 'visualize'

### ISSUE THREAD

**Issue by liuzeyang0311** [SuperKogito/spafe#27]
when I use “vis.visualize(gfccs, 'LMFCC Coefficient Index','Frame Index')” it gives
AttributeError: module 'spafe.utils.vis' has no attribute 'visualize'

**Comment by SuperKogito** [comment]
without no meaningful example, I am unable to reproduce or inspect this. Something is probably wrong with your import. 
Anyhow you should use version `v0.2.0` now. Enough examples can be found in the docs: https://superkogito.github.io/spafe/v0.2.0/index.html
