### ISSUE TITLE
TypeError: dct(): incompatible function arguments for bfcc, gfcc, pncc, mfcc

### ISSUE THREAD

**Issue by rbsingh13** [SuperKogito/spafe#30]
Hello, for each of the feature extraction mentioned, I am getting the error:

`TypeError: dct(): incompatible function arguments.`

I am not sure if it is due to the fact that I have to include the library 

`from scipy.io import wavfile`

However, I do not get any errors with the `lpc` and `lpcc` feature extraction.  

Is there a fix to prevent these errors?

**Comment by SuperKogito** [comment]
This is most probably a versions incompatibility issue. Please use the specific versions: 
    
    - NumPy == 1.17.2
    - SciPy == 1.3.1

Let me me know if this fixes it so I can edit the Readme accordingly.
