### ISSUE TITLE
IndexError: index 257 is out of bounds for axis 1 with size 257

### ISSUE THREAD

**Issue by Helias** [SuperKogito/spafe#32]
`IndexError: index 257 is out of bounds for axis 1 with size 257`

Sometimes I get this issue because the index `j-2` overcome the max length of fbank, I used a try-except to ignore the issue but I don't think that is really a smart code.

```
  File "/usr/local/lib/python3.9/site-packages/spafe/features/bfcc.py", line 120, in bfcc
    bark_fbanks_mat = bark_filter_banks(nfilts=nfilts,
  File "/usr/local/lib/python3.9/site-packages/spafe/fbanks/bark_fbanks.py", line 96, in bark_filter_banks
    fbank[j - 2, i] = c * Fm(fb, fc)
IndexError: index 257 is out of bounds for axis 1 with size 257
```

spafe version: 0.1.1
python version: 3.9.12

**Comment by SuperKogito** [comment]
Thank you for reporting this. 
I am actually reviewing the whole library and trying to fix all these issue in the upcoming version .0.1.3. 
I should be able to publish it in a month at the latest.
