### ISSUE TITLE
IndexError: index 3806427 is out of bounds for axis 0 with size 39168

### ISSUE THREAD

**Issue by Helias** [SuperKogito/spafe#35]
```
  File "/usr/local/lib/python3.9/site-packages/spafe/features/spfeats.py", line 279, in extract_feats
    feats["mode_frequency"] = frequencies[amplitudes.argmax()]
IndexError: index 3806427 is out of bounds for axis 0 with size 39168
```

```
  File "/usr/local/lib/python3.9/site-packages/spafe/features/spfeats.py", line 270, in extract_feats
    feats["peak_frequency"] = frequencies[np.argmax(amplitudes)]
IndexError: index 3806427 is out of bounds for axis 0 with size 39168
```

We are getting in the wrong way the `argmax()` of `amplitudes` when `amplitudes` dimensions is greater than `1`.

Moreover, mode_frequency and peak_frequency have the same value, because amplitudes.argmax() and np.argmax(amplitudes) are the same, but this is a different issue https://github.com/SuperKogito/spafe/issues/34

**Comment by Helias** [comment]
I "solved" this issue by reducing the audio channels to 1, using `ffmpeg -i input.mp3 -ac 1 output.mp3` but of course, this remove some data from the audio.

This library unfortunately does not support file audio with multiple channels.

**Comment by SuperKogito** [comment]
In the readme it is specified that spafe only handles mono signals (signals with one channel only) 

> spafe aims to simplify features extractions from **mono** audio files.

I do not see the need to change, since you can split or merge the channels with FFmpeg or SciPy. Also most audio processing libraries out there deals with mono cases.

**Comment by Helias** [comment]
ok, thank tou!
