### ISSUE TITLE
Cannot get the paper from LFCC

### ISSUE THREAD

**Issue by JJ-Guo1996** [SuperKogito/spafe#50]
hi!  i cannot get the paper from  http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.63.8029&rep=rep1&type=pdf based on LFCC???

**Comment by SuperKogito** [comment]
I just emailed the website for another link as I couldn't find the paper with it doi.

**Comment by SuperKogito** [comment]
The link you referenced is related to the MFCC implementation. Unfortunately I can no longer find it, hence this is imo an adequate replacement [COMPUTING MEL-FREQUENCY CEPSTRAL COEFFICIENTS
ON THE POWER SPECTRUM](https://www-i6.informatik.rwth-aachen.de/publications/download/474/MolauSirkoPitzMichaelSchl%7Bu%7DterRalfNeyHermann--ComputingMel-FrequencyCepstralCoefficientsOnThePowerSpectrum--2001.pdf). In case you are looking for a good tutorial on how to implement MFCC, I highly recommend this https://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html
