### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'.  in spafe.features.ngcc.ngcc()

### ISSUE THREAD

**Issue by zakaria-kabir** [SuperKogito/spafe#57]
**spafe.features.ngcc.ngcc(....., low_freq: [Optional] = None)** but ***doc says, low_freq defalut is 0***. Also no where in the function the value has been set.
This occurs error in: (if low_freq argument not passed)
* gammatone_filter_banks(nfilts, nfft, fs, low_freq, high_freq, scale, order, conversion_approach)
    180 
    181     # run checks
--> 182     if low_freq < 0:
    183         raise ParameterError(ErrorMsgs["low_freq"]) *

![image](https://user-images.githubusercontent.com/91650627/219829202-cc839097-dfca-44fc-8f41-81e7ec692239.png)

**Comment by SuperKogito** [comment]
This is a good catch. I already found the issue and I will be releasing the fix asap. 
Thank you for reporting :heart:
