### ISSUE TITLE
All documentations are outdated

### ISSUE THREAD

**Issue by GoMapur** [SuperKogito/spafe#59]
Hello, please update https://spafe.readthedocs.io/ as documentations are outdated. For example, 

this is the correct useage of lfcc after looking at the github code
`lfcc(sig=audio, fs=fs, high_freq=8000, normalize="mvn")`

However on readthedocs it is said normalize should be set as either 0 or 1

**Comment by SuperKogito** [comment]
The official documentation is no longer on readthedocs.
Instead you find it here https://superkogito.github.io/spafe/ as stated in the README.
