### ISSUE TITLE
Possible Issue with MVN Calculation in the Code

### ISSUE THREAD

**Issue by xuke57** [SuperKogito/spafe#65]
According to the comments in the code file (["mvn"](https://github.com/SuperKogito/spafe/blob/master/spafe/utils/cepstral.py) ), the mathematical expression for MVN is (line 34): 
$$x^{\prime}=\frac{x-{average}(x)}{{std}(x)}$$
However, in the code implementation, MVN is defined as (line 51):
```
"mvn": (x - np.mean(x, axis=0)) / np.std(x)
```
Here, the variance (np.std) is computed based on the feature matrix x, while the mean (np.mean) is calculated based on a single dimension. This does not entirely match the MVN as described in the mathematical expression, where both mean and variance should be computed based on the same thing (I guess it should be a single dimension as what CMVN 
 should do), such as:
```
"mvn": (x - np.mean(x, axis=0)) / np.std(x, axis=0)
```

**Comment by SuperKogito** [comment]
Although this seems like a valid observation, but in practicality this makes no difference. 
If you look at the docs: 
- https://numpy.org/doc/stable/reference/generated/numpy.mean.html
- https://numpy.org/doc/stable/reference/generated/numpy.std.html

you will realize that the use of 0 is equivalent to the default case which is the same in both cases (flattened array).

> The default is to compute the standard deviation of the flattened array.

> The default is to compute the mean of the flattened array.


Therefore without a clear counter example,  the code is fine the way it is.

**Comment by xuke57** [comment]
I compared the results after defining the axis. It looks like defining axis is still necessary. The code and results are as follows:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy.io import wavfile
from spafe.features.mfcc import mfcc
from spafe.utils.preprocessing import SlidingWindow

wav_path = '002.wav'
sr_sig = wavfile.read(wav_path)
speech_feature_matrix = mfcc(sig=sr_sig[1], fs=sr_sig[0],
                               pre_emph=1, pre_emph_coeff=0.97,
                               window=SlidingWindow(0.015, 0.005, "hamming"),
                               nfilts=128, nfft=2048,
                               low_freq=0, high_freq=8000,
                               normalize=None)
spafemvn = (speech_feature_matrix - np.mean(speech_feature_matrix, axis=0)) / np.std(speech_feature_matrix)
cmvn = (speech_feature_matrix - np.mean(speech_feature_matrix, axis=0)) / np.sqrt(np.var(speech_feature_matrix, axis=0))

fig, axs = plt.subplots(2, 1)
axs[0].imshow(spafemvn.T, origin='lower', aspect='auto')
axs[0].set_title('spafe mvn')
axs[1].imshow(cmvn.T, origin='lower', aspect='auto')
axs[1].set_title('cmvn')
plt.show()
```
<img width="705" alt="截屏2024-04-21 12 42 24" src="https://github.com/SuperKogito/spafe/assets/33355811/c6b3831d-90cf-4875-b0e2-280e005afbe8">

**Comment by SuperKogito** [comment]
I genuinely do not understand what are you trying to prove with the above. You are comparing a normalization based on Standard deviation with one using the Sqrt of the variance. So I do not see your point. 

Nevertheless, you made a fair point in your very first remark. After some testing, the default setting is not the same as axis=0 so all the axis=0 assignments in the mean functions in the following should be removed.  https://github.com/SuperKogito/spafe/blob/b6b1428df52694c95bb295a6ec291ae442053fcc/spafe/utils/cepstral.py#L51
